apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: odin
  namespace: '1009941290130'
  selfLink: /apis/serving.knative.dev/v1/namespaces/1009941290130/services/odin
  uid: 5c04734c-1b0f-4fce-8b3a-03dbb8df5bdb
  resourceVersion: AAYKHTbdJDI
  generation: 2
  creationTimestamp: '2023-11-14T13:59:29.199737Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: 7d6d33b4-3d5c-407e-81f5-f5da1c218d9f
    gcb-trigger-region: global
    cloud.googleapis.com/location: europe-west4
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: mjj.vollebregt@cbs.nl
    serving.knative.dev/lastModifier: mjj.vollebregt@cbs.nl
    run.googleapis.com/operation-id: 751416a6-056b-4e58-8593-644d74ae01e4
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 1009941290130-compute@developer.gserviceaccount.com
      containers:
      - name: placeholder-1
        image: gcr.io/cloudrun/placeholder
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
