runtime: aspnetcore
env: flex

instance_class: F2
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

threadsafe: true
handlers:
- url: /
  static_files: ClientApp/dist/index.html
  upload: ClientApp/dist/index.html
- url: /
  static_dir: ClientApp/dist
options:
  logging: CLOUD_LOGGING_ONLY
