steps:
# .NET Core 2.0 by default restores before any build, so we can
# combine the restore and publish operations in a single statement.
- name: 'microsoft/dotnet:sdk'
  entrypoint: 'dotnet'
  args: [ 'publish', '-c', 'Release' ]

# Build the app image.
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/Odin:6.0', '.' ]
  dir: './bin/Release/net6.0/publish'

# Publish the app.
images: [ 'gcr.io/$PROJECT_ID/Odin:6.0' ]

options:
  logging: CLOUD_LOGGING_ONLY
