# cloudbuild.yaml

steps:
  # Step 1: Use the official .NET SDK image
  - name: 'mcr.microsoft.com/dotnet/sdk:6.0'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o /workspace/app

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/core_backend:$COMMIT_SHA'
      - '.'

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/core_backend:$COMMIT_SHA'

  # Step 4: Deploy the application (example: deploy to Cloud Run)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'odin'
      - '--image'
      - 'gcr.io/$PROJECT_ID/core_backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/core_backend:$COMMIT_SHA'
