steps:
- name: 'microsoft/dotnet:sdk'
  entrypoint: 'dotnet'
  args: [ 'publish', '-c', 'Release' ]

# Build the app image.
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/core_backend', '.' ]
  dir: './bin/Release/net6.0/publish'

# Publish the app.
images: [ 'gcr.io/$PROJECT_ID/core_backend' ]

options:
  logging: CLOUD_LOGGING_ONLY
